### ISSUE TITLE
Setup problems

### ISSUE THREAD

**Issue by Knallli** [yeonholee50/AmpyFin#18]
I face a lot of issues when settings this up.

First off, where do I place the config.py? In the base directory? running mongo_setup.py results in a No module named config when doing this.

I also get AttributeError: module 'datetime' has no attribute 'now' when running mongo_setup.py fixing this by adding "from datetime import datetime"

Next error is this: 

python3.10 helper_files/mongo_setup.py
Traceback (most recent call last):
  File "/Users/x/Documents/trading/AmpyFin/helper_files/mongo_setup.py", line 90, in <module>
    initialize_market_setup()
  File "/Users/x/Documents/trading/AmpyFin/helper_files/mongo_setup.py", line 83, in initialize_market_setup
    collection.insert_one({"market_status": "closed"})
  File "/opt/homebrew/lib/python3.10/site-packages/pymongo/synchronous/collection.py", line 401, in __call__
    raise TypeError(
TypeError: 'Collection' object is not callable. If you meant to call the 'insert_one' method on a 'Database' object it is failing because no such method exists.

Help is appreciated!!

**Comment by yeonholee50** [comment]
I had datetime preinstalled from other projects but just updated requirements.txt to help with this. Thanks for bringing this up. also you have to put config in the base directory.

**Comment by Knallli** [comment]
Thanks!

however I cannot run the mongo setup if the config is only in the base directory. What python version are you using for this? 3.10-3.12 all have the same behaviour. For it to not error out instantly I have to copy the config.py into the helper folder

**Comment by yeonholee50** [comment]
yes you are right. this isn't python version i have moved the set up to base and it should work now. Thank you for pointing this out and my apologies. Please let me know if the set up works. Thank you!! :)

**Comment by ven7782** [comment]
I had the same issues and I fixed it myself. I can issue a PR later today.

**Comment by Knallli** [comment]
Some problems still persist with the changes. I changed Line 4 to "from datetime import datetime"

I still get TypeError: 'Collection' object is not callable. If you meant to call the 'insert_one' method on a 'Database' object it is failing because no such method exists. from the function in line 83

**Comment by Knallli** [comment]
I know.. I did not want to open another issue for this. It’s two seperate problems

**Comment by ven7782** [comment]
Wait for my PR later in the day and do a fresh pull after that.

**Comment by Knallli** [comment]
database preperation works now by changing line 82 to `collection = db.market_status`

**Comment by yeonholee50** [comment]
I'll close the issue as I just merged the PR. Great work
